[platformio]
core_dir = .pio-core
cache_dir = .pio-cache
default_envs = waveshare_esp32_s3_lcd_4_3

[env:waveshare_esp32_s3_lcd_4_3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
extra_scripts = pre:scripts/esp32s3_toolchain.py
monitor_speed = 115200
upload_speed = 921600
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_build.partitions = default_16MB.csv
lib_ldf_mode = chain
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -mdynconfig=xtensa_esp32s3.so
    -Isrc
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLV_CONF_SKIP
    -DLV_COLOR_DEPTH=16
    -DLV_USE_LOG=0
    -DLV_FONT_MONTSERRAT_16=1
    -DLV_FONT_MONTSERRAT_18=1
    -DLV_FONT_MONTSERRAT_20=1
    -DLV_FONT_MONTSERRAT_24=1
    -DLV_FONT_MONTSERRAT_32=1
    -DLV_FONT_MONTSERRAT_48=1
